/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContactRouteImport } from './routes/_authenticated/contact'
import { Route as AuthenticatedCotisationsRouteImport } from './routes/_authenticated/cotisations'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactRoute = AuthenticatedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotisationsRoute =
  AuthenticatedCotisationsRouteImport.update({
    id: '/cotisations',
    path: '/cotisations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/connexion': typeof ConnexionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/contact': typeof AuthenticatedContactRoute
  '/cotisations': typeof AuthenticatedCotisationsRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/contact': typeof AuthenticatedContactRoute
  '/cotisations': typeof AuthenticatedCotisationsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/_authenticated/contact': typeof AuthenticatedContactRoute
  '/_authenticated/cotisations': typeof AuthenticatedCotisationsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/connexion' | '/mentions-legales' | '/contact' | '/cotisations'
  fileRoutesByTo: FileRoutesByTo
  to: '/connexion' | '/mentions-legales' | '/contact' | '/cotisations' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connexion'
    | '/mentions-legales'
    | '/_authenticated/contact'
    | '/_authenticated/cotisations'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact': {
      id: '/_authenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthenticatedContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotisations': {
      id: '/_authenticated/cotisations'
      path: '/cotisations'
      fullPath: '/cotisations'
      preLoaderRoute: typeof AuthenticatedCotisationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactRoute: typeof AuthenticatedContactRoute
  AuthenticatedCotisationsRoute: typeof AuthenticatedCotisationsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactRoute: AuthenticatedContactRoute,
  AuthenticatedCotisationsRoute: AuthenticatedCotisationsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
